### ISSUE TITLE
推理的时候爆内存了，我还是colab pro+

### ISSUE THREAD

**Issue by PPSh-1895** [innnky/so-vits-svc#81]
我在推理的时候报了
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 11.15 GiB (GPU 0; 39.59 GiB total capacity; 31.42 GiB already allocated; 4.90 GiB free; 32.94 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF。我感觉这不太正常，有无高手指导一下。

**Comment by whdycdq** [comment]
推理的音频太大了，爆显存了，把音频切开然后一个一个推理，最后再合并到一起去

**Comment by PPSh-1895** [comment]
> 推理的音频太大了，爆显存了，把音频切开然后一个一个推理，最后再合并到一起去

多谢，问题解决了！

**Comment by yabo083** [comment]
@PPSh-1895 请问在您在colab上是怎么推理的，可否说明一下？
